default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: yusuke
  password: yusuke

development:
  <<: *default
  database: yusuke_development

test:
  <<: *default
  database: yusuke_test

production:
  <<: *default
  database: yusuke_production
