default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: yusuke_development

test:
  <<: *default
  database: yusuke_test

production:
  <<: *default
  adapter: postgresql #追加
  database: db/yusuke_production.postgresql